{
 "title": "PowerData",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Watt",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DWS74_Power_curr\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Avg. Idle Watt",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power-bucket\")\r\n  |> range(start: -30d)  // Adjust the time range as needed\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DWS74_Power_curr\")\r\n  |> filter(fn: (r) => r[\"_value\"] >= 40.0 and r[\"_value\"] <= 280.0)\r\n  |> mean(column: \"_value\")\r\n  |> yield(name: \"average_idle_power\")\r\n"
    }
   ]
  },
  {
   "title": "Watt over time",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"power-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DWS74_Power_curr\")\r\n"
    }
   ]
  },
  {
   "title": "kWh Consumption per hour",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"power-bucket\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DWS74_Total\")\r\n  |> aggregateWindow(every: 1h, fn: max, createEmpty: false)\r\n  |> difference()\r\n  |> yield(name: \"hourly_energy_consumption\")\r\n"
    }
   ]
  },
  {
   "title": "Stromkosten pro Tag",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"power-bucket\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DWS74_Total\")\r\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\r\n  |> difference()\r\n  |> map(fn: (r) => ({ r with _value: (r._value * 0.3007) + 0.010 }))\r\n  |> yield(name: \"daily_energy_cost\")"
    }
   ]
  },
  {
   "title": "Cost so far",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"power-bucket\")\r\n  |> range(start: 0)  // Start from the beginning of your data collection\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DWS74_Total\")\r\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\r\n  |> difference()\r\n  |> map(fn: (r) => ({ r with _value: 1 }))  // Replace each daily value with 1\r\n  |> sum(column: \"_value\")\r\n  |> yield(name: \"number_of_days\")\r\n"
    },
    {
     "query": "from(bucket: \"power-bucket\")\r\n  |> range(start: 0)  // Start from the beginning of your data collection\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DWS74_Total\")\r\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\r\n  |> difference()\r\n  |> map(fn: (r) => ({ r with _value: (r._value * 0.3007) + 0.010 }))\r\n  |> sum(column: \"_value\")\r\n  |> yield(name: \"total_energy_cost\")\r\n"
    }
   ]
  }
 ]
}